### ISSUE TITLE
Talk - Do zero à produção

### ISSUE THREAD

**Issue by rogerfernandes** [joinville-gophers/cfp#3]
# Do zero à produção

**Tipo:** Talk

**Descrição:** Vou falar sobre meu primeiro contato com o Golang, já desenvolvendo um micro-serviço para Produção. Comentarei as dificuldades, curiosidades e percepções que tive, sendo um programador Java transitando para o Golang.

**Duração:** Short talk (~30min)

## Informações pessoais

**Nome:** Roger Fernandes

**Sobre:** Trabalho com desenvolvimento de software a mais ou menos 8 anos, principalmente com Java em sistemas Web. No meu tempo livre gosto de ler blogs, escutar podcasts, ver vídeos sobre as mais diversas áreas, como programação, arduino, eletrônica, impressão 3d, mecânica automobilística entre outros.

---

_Como votar:_

- reação com :+1: se você quer ouvir sobre esse tópico
- reação :-1: se você não quiser

**Comment by caarlos0** [comment]
Maaasssaa!!

**Comment by caarlos0** [comment]
feito em https://github.com/joinville-gophers/discussions/issues/3

**Comment by caarlos0** [comment]
Obrigado @rogerfernandes !

**Comment by rogerfernandes** [comment]
[Do Zero à Produção.pdf](https://github.com/joinville-gophers/cfp/files/3350736/Do.Zero.a.Producao.pdf)
