### ISSUE TITLE
Talk - Introdução à gRPC em Go

### ISSUE THREAD

**Issue by rodrigobahiense** [joinville-gophers/cfp#4]
# Introdução à gRPC em Go

**Tipo:** Talk

**Descrição:** Esta talk fará uma breve introdução à tecnologia gRPC (https://grpc.io/) e em seguida demonstrará alguns exemplos de casos de uso utilizando a linguagem Go.

**Duração:** Short talk (~30min)

## Informações pessoais

**Nome:** Rodrigo Amorim Bahiense

**Sobre:** Sou sysadmin (Linux) há aprox. 15 anos e comecei a desenvolver software para melhorar o tempo de execução de alguns scripts. Mais tarde surgiu a necessidade de implementar aplicações cada vez mais complexas que se tornaram sistemas cliente-servidor, e faço isso desde então.

---

_Como votar:_

- reação com :+1: se você quer ouvir sobre esse tópico
- reação :-1: se você não quiser

**Comment by caarlos0** [comment]
Massa @zugl!

Quer falar sobre isso no próximo meetup já (vulgo amanhã)? (temos um slot vago ainda hehe)

**Comment by rodrigobahiense** [comment]
@caarlos0 
Se possível seria bom! =)

**Comment by caarlos0** [comment]
@zugl entao fechou! 

Já vou ajustar o meetup.com :)

**Comment by caarlos0** [comment]
Feito -> https://www.meetup.com/Joinville-Go-Meetup/events/247548485/

**Comment by caarlos0** [comment]
@zugl tudo certo pra hoje? Precisa de algo da minha parte?

[]'s

**Comment by rodrigobahiense** [comment]
@caarlos0 Tudo certo, sem impedimentos!

**Comment by caarlos0** [comment]
Feito em https://github.com/joinville-gophers/discussions/issues/3 

Obrigado @zugl !
